# Generated by Django 5.1.1 on 2024-10-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waypoint_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='location_state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
